name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "Breaking Changes"
    labels:
      - "breaking-change"
  - title: "New Features"
    labels:
      - "enhancement"
      - "feature"
  - title: "Bug Fixes"
    labels:
      - "bug"
      - "fix"
  - title: "Documentation"
    labels:
      - "documentation"
  - title: "Maintenance"
    labels:
      - "chore"
      - "dependencies"
      - "refactor"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - "breaking-change"
  minor:
    labels:
      - "enhancement"
      - "feature"
  patch:
    labels:
      - "bug"
      - "fix"
      - "chore"
      - "dependencies"
      - "documentation"
      - "refactor"
  default: patch

template: |
  ## Changes

  $CHANGES
